# -*- coding: utf-8 -*-
"""alphapet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-KmjXyjRS8rM60asDSCikpRUQoJ6-0Js
"""


import numpy as np
import pandas as pd

with open("/home/abdo_khattab/Documents/work/final project/ا لحد خ", "r") as f:
    file=f.read()
    file=file.strip()
    file=file.replace(' ','')
    inputs=file.splitlines()
    for i in inputs:
      inputs[inputs.index(i)]=i.split(',')

df = pd.DataFrame(inputs, columns = ['letter','f1','f2','f3','f4','f5','a1','a2','a3','a4','a5','a6'])

df['letter']=df['letter'].replace(['a'],'ا')
df['letter']=df['letter'].replace(['b'],'ب')
df['letter']=df['letter'].replace(['c'],'ت')
df['letter']=df['letter'].replace(['d'],'ث')
df['letter']=df['letter'].replace(['e'],'ح')
df['letter']=df['letter'].replace(['f'],'ج')
df['letter']=df['letter'].replace(['g'],'خ')
print(df['a2'])